---
title: "Lecture5 Activity1: Linear Regression"
output:
  html_document: 
    toc: true
    toc_float: true
---
<br>

### Question 1

You can download the dataset [HERE](files/lec5/tumorsize.csv). 

You are provided with a tumor size dataset, and your task is to perform multiple linear regression using Prism Graphpad. The dataset contains three variables: `TumorSize` (dependent variable), `Gene1` and `Gene2` (independent variables). Follow the steps below to conduct the analysis and interpret the results:

a. Perform multiple linear regression using Prism Graphpad, with `TumorSize` as the dependent variable and `Gene1` and `Gene2` as independent variables.

b. Display the summary of the linear regression model to obtain the estimated coefficients for `Gene1` and `Gene2`.

c. Interpret each coefficient obtained from the regression model.



<br>

<details>
  <summary><strong>Answer to Question 1:</strong></summary>
  
<br>


</details>
<br><br>

### Question 2


<br>

<details>
  <summary><strong>Answer to Question 2:</strong></summary>
  
<br>



</details>
<br><br>

<a href="schedule.html">< Go Back</a>
